[build]
    functions="functions"

[[redirects]]
    to="/.netlify/functions/api:splat"
    from="/*"
    status=200 

    [functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"